---

- fail: msg="NodeJS is only supported for Ubuntu"
  when: ansible_distribution != 'Ubuntu'

- name: Add apt key for the nodesource repository
  apt_key: url="https://deb.nodesource.com/gpgkey/nodesource.gpg.key" state=present
  tags:
    - nodejs

- name: Add the nodesource apt repository
  apt_repository: repo="deb https://deb.nodesource.com/iojs_2.x trusty main" state=present
  tags:
    - nodejs

- name: Install NodeJS packages
  apt: name=iojs state=latest
  tags:
    - nodejs

